# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/

title: Scott H. Hawley (alt. blog via fastpages)
description: An alternate copy of my development blog, using fastpages. If successful I will replace the main blog with this
github_username: drscotthawley
# you can comment the below line out if your repo name is not different than your baseurl
github_repo: "devblog3"

# OPTIONAL: override baseurl and url if using a custom domain
url: "https://drscotthawley.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/devblog3" # the subpath of your site, e.g. "/blog".  WARNING: if you are not using a custom domain, the baseurl *must* be set to your repo name.

# Email and twitter are optional:
email:
twitter_username: "@drscotthawley"

# Set this to true to get LaTeX math equation support
use_math: true

# Add your Google Analytics ID here if you have one and want to use it
google_analytics:

# Everything below here should be left alone. Modifications may break fastpages
theme: minima
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-octicons
  - jekyll-github-metadata
  - jekyll-toc
  - jekyll-twitter-plugin
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-redirect-from

titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true

highlighter: rouge
markdown: kramdown
kramdown:
  math_engine: katex
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge
